---
- hosts: all
  become: yes
  gather_facts: yes
  vars_files:
    - ./vars/variables.yaml
  roles:
    - role: k8s-prereqs 
      when: ansible_facts['os_family'] == "Debian"
    - role: k8s-prereqs-ec2
      when: ansible_facts['bios_vendor'] == "Amazon EC2"
    - role: k8s-prereqs-pi
      when: ansible_facts['bios_vendor'] == "Raspberry Pi"
